### ISSUE TITLE
Add an outlet feature to store outlet information

### ISSUE THREAD

**Issue by SunBangjie** [CS2103JAN2018-W14-B2/main#22]
OutletInformation class contains essential information of the outlet. The information includes outlet name, master password, operating hours, shifts, standard number of employees per shift and timetable.

Commands related to this class:
1. View command to display information in the GUI
2. Edit command for basic information such as name and operating hours
3. Edit command for timetable
4. Change master password command

Classes needed from teammates:
1. Password
2. Timetable

What needs to be done?
1. Create OutletInformation class to store basic information with default values. (Model)
2. Store all above information using another file. (Storage)
3. Create above commands. (Logic)
4. Display information in the GUI. (UI)
5. Highlight edited information with another color. (UI)

**Comment by koo1993** [comment]
Too many things in this issue. Maybe you want to break down into smaller issue referring back to this issue

**Comment by shanwpf** [comment]
Perhaps you can format it to look like #24 so that it's more organized.
